name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flet
        run: |
          pip install --upgrade pip
          pip install flet

      - name: Build APK
        run: |
          # Собираем APK с доступом к памяти
          flet build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: drip-client-v1.3
          path: build/apk/*.apk
